services:
  mysql:
    build: ./db
    image: mysql-db:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pbooth
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    image: aakasha-backend:latest
    container_name: aakasha-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    image: aakasha-frontend:latest
    container_name: aakasha-frontend
    restart: always
    env_file:
      - ./frontend/Aakasha_ui/.env

volumes:
  mysql_data:

