services:
  
  backend:
    build: ./backend
    image: aakasha-backend:latest
    container_name: aakasha-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    image: aakasha-frontend:latest
    container_name: aakasha-frontend
    restart: always
    env_file:
      - ./frontend/Aakasha_ui/.env

volumes:
  mysql_data:

