namespace: aakasha-prod

frontend:
  replicaCount: 3

  image:
    repository: 185427174197.dkr.ecr.us-east-1.amazonaws.com/aakasha-frontend
    tag: latest

  env:
    NEXT_PUBLIC_BACKEND_URL: http://aakasha-backend:3005

backend:
  replicaCount: 3

  image:
    repository: 185427174197.dkr.ecr.us-east-1.amazonaws.com/aakasha-backend
    tag: latest


