namespace: aakasha-dev

frontend:
  replicaCount: 1

  image:
    tag: latest

  env:
    NEXT_PUBLIC_BACKEND_URL: http://aakasha-backend:3005

backend:
  replicaCount: 1

  image:
    tag: latest

mysql:
  database: pbooth
  username: pbooth
