apiVersion: v1
kind: Service
metadata:
  name: aakasha-backend
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app: aakasha-backend

  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
