apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aakasha-mysql
  namespace: {{ .Values.namespace }}

spec:
  serviceName: aakasha-mysql
  replicas: 1

  selector:
    matchLabels:
      app: aakasha-mysql

  template:
    metadata:
      labels:
        app: aakasha-mysql

    spec:
      containers:
        - name: mysql

          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}

            - name: MYSQL_USER
              value: {{ .Values.mysql.username | quote }}

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aakasha-mysql-secret
                  key: mysql-password

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aakasha-mysql-secret
                  key: mysql-password

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 20Gi
