apiVersion: v1
kind: Service
metadata:
  name: aakasha-mysql
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app: aakasha-mysql

  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
